### ISSUE TITLE
Добавить healthcheck'и

### ISSUE THREAD

**Issue by PlugFox** [jugatsu/onec-docker#22]
Типа такого надо добавить

```yaml
healthcheck:
  test: curl --fail -s http://127.0.0.1:8080/health || exit 1
  interval: 30s
  timeout: 15s
  retries: 3
```

Можно в образы даже типа таких скриптов добавить
https://github.com/docker-library/healthcheck

Чтоб проверять в тч и жизнеспособность постгресов и всякого такого, а не только того где можно хттп ручки сделать
